Stable release 1.0.0

diff --git a/.github/workflows/continuous_integration.yml b/.github/workflows/continuous_integration.yml
--- a/.github/workflows/continuous_integration.yml
+++ b/.github/workflows/continuous_integration.yml
@@ -3,32 +3,62 @@ name: Continuous Integration
 on: [push, pull_request]
 
 jobs:
-  format:
+  check:
     runs-on: ubuntu-latest
     timeout-minutes: 5
-    container:
-      image:  google/dart:beta
     steps:
       - uses: actions/checkout@v2
-      - name: Ensure idiomatic Dart source code formatting
-        run: dartfmt -w --set-exit-if-changed .
-
-  # We don't have any meaningful tests at the moment.
+      - uses: actions/setup-java@v1
+        with:
+          java-version: '12.x'
+      - uses: subosito/flutter-action@v1
+        with:
+          channel: 'stable'
+      - name: Get dependencies
+        run: flutter pub get
+      - name: Verify source code is formatted
+        run: flutter format --set-exit-if-changed .
+      - name: Verify there are no analyzer errors
+        run: flutter analyze --fatal-infos --fatal-warnings .
+      - name: Verify all tests pass
+        run: flutter test --coverage
+      - name: Verify example app builds
+        run: cd example && flutter build apk
+      - uses: codecov/codecov-action@v1.0.0
+        name: Upload coverage to codecov.io
+        with:
+          flags: unittests
+          file: coverage/lcov.info
+          token: ${{ secrets.CODECOV_TOKEN }}
 
   publish:
     runs-on: ubuntu-latest
     timeout-minutes: 5
-    needs: [format]
-    if: github.ref == 'refs/heads/master'
-    container:
-      image:  google/dart:beta
+    needs: [check]
+    if: github.ref == 'refs/heads/main'
+    # Continue on error doesn't seem to work?
+    # Using || true for publishing
+    # continue-on-error: true
     steps:
       - uses: actions/checkout@v2
+      - name: Install Dart
+        run: |
+          sudo apt-get update
+          sudo apt-get install apt-transport-https
+          sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
+          sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
+          sudo apt-get update
+          sudo apt-get install dart
+          export PATH="$PATH:/usr/lib/dart/bin"
       - name: Setup credentials
         run: |
           mkdir -p ~/.pub-cache
-          echo '${{ secrets.PUB_CREDENTIALS_JSON }}' > ~/.pub-cache/credentials.json
-      - name: Publish the package to pub.dartlang.org
-        run: pub publish --force || true
+          echo ${{ secrets.PUB_CREDENTIALS_JSON }} > ~/.pub-cache/credentials.json
+      - name: Publish the package
+        run: |
+          export version=v$(grep "version: " pubspec.yaml | cut -c 10-)
+          dart pub publish --force && (git tag $version && git push origin $version && gh release create $version) || true
+        env:
+          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
       - name: Delete credentials
         run: rm ~/.pub-cache/credentials.json
